name: kassel_app
description: Kassel Academy Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.5
  record: ^6.1.2
  path_provider: ^2.1.4
  audioplayers: ^6.5.1
  permission_handler: ^11.3.0
  change_app_package_name: ^1.5.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kassel_logo.png
    - assets/images/learnimg.png
    - assets/images/englishprep.png
